branch-defaults:
  production:
    environment: ama-cymru
    group_suffix: null
global:
  application_name: ama-cymru
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.11.2
  default_region: eu-central-1
  profile: null
  repository: null
  sc: git
